# -*- coding: utf-8 -*-
"""EasyTask_CSE425_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7vXuRee26Fh-XgaETCmD7XYCg7eSrCf
"""

import os

dataset_path = '/content/drive/MyDrive/CSE425 Project/genres_original'

# List contents of the dataset directory
if os.path.exists(dataset_path):
    print(f"Contents of '{dataset_path}':")
    for item in os.listdir(dataset_path):
        print(item)

    # Optionally, list contents of a subdirectory to see audio files
    # For example, let's pick the first genre directory if available
    subdirs = [os.path.join(dataset_path, d) for d in os.listdir(dataset_path) if os.path.isdir(os.path.join(dataset_path, d))]
    if subdirs:
        first_subdir = subdirs[0]
        print(f"\nContents of a sample subdirectory ('{os.path.basename(first_subdir)}'):")
        for i, item in enumerate(os.listdir(first_subdir)):
            if i < 5: # Limit to first 5 items for brevity
                print(item)
            else:
                print(f"... and {len(os.listdir(first_subdir)) - 5} more files.")
                break
else:
    print(f"Error: The directory '{dataset_path}' does not exist.")

import warnings
warnings.filterwarnings("ignore")

!pip install librosa
import os
import numpy as np
import librosa
from tqdm import tqdm
DATASET_PATH = '/content/drive/MyDrive/CSE425 Project/genres_original'

def extract_mfcc(file_path, n_mfcc=13, duration=30):
    """
    Extract MFCC features from an audio file.
    Returns a fixed-length MFCC vector.
    """
    try:
        y, sr = librosa.load(file_path, duration=duration)
        mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
        mfcc_mean = np.mean(mfcc.T, axis=0)  # (n_mfcc,)
        return mfcc_mean
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

X = []          # MFCC features
y_labels = []   # Genre labels (ONLY for evaluation, not training)

for genre in tqdm(os.listdir(DATASET_PATH)):
    genre_path = os.path.join(DATASET_PATH, genre)

    if not os.path.isdir(genre_path):
        continue

    for file in os.listdir(genre_path):
        if file.endswith('.wav'):
            file_path = os.path.join(genre_path, file)
            mfcc = extract_mfcc(file_path)

            if mfcc is not None:
                X.append(mfcc)
                y_labels.append(genre)

X = np.array(X)
y_labels = np.array(y_labels)

print("MFCC feature shape:", X.shape)
print("Number of labels:", y_labels.shape)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Mean (approx):", X_scaled.mean(axis=0))
print("Std (approx):", X_scaled.std(axis=0))
np.save('mfcc_features_scaled.npy', X_scaled)

import tensorflow as tf
from tensorflow.keras import layers, Model
import numpy as np
input_dim = X_scaled.shape[1]   # should be 13 (MFCC)
latent_dim = 16                 # you can choose 8 / 16 / 32
def sampling(args):
    z_mean, z_log_var = args
    epsilon = tf.random.normal(shape=tf.shape(z_mean))
    return z_mean + tf.exp(0.5 * z_log_var) * epsilon
inputs = layers.Input(shape=(input_dim,))
x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(32, activation='relu')(x)

z_mean = layers.Dense(latent_dim, name='z_mean')(x)
z_log_var = layers.Dense(latent_dim, name='z_log_var')(x)

z = layers.Lambda(sampling, name='z')([z_mean, z_log_var])

encoder = Model(inputs, [z_mean, z_log_var, z], name='encoder')
encoder.summary()

latent_inputs = layers.Input(shape=(latent_dim,))
x = layers.Dense(32, activation='relu')(latent_inputs)
x = layers.Dense(64, activation='relu')(x)
outputs = layers.Dense(input_dim)(x)

decoder = Model(latent_inputs, outputs, name='decoder')
decoder.summary()

class VAE(Model):
    def __init__(self, encoder, decoder, **kwargs):
        super(VAE, self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder

    def train_step(self, data):
        if isinstance(data, tuple):
            data = data[0]

        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)

            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(tf.square(data - reconstruction), axis=1)
            )

            kl_loss = -0.5 * tf.reduce_mean(
                tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1)
            )

            total_loss = reconstruction_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))

        return {
            "loss": total_loss,
            "reconstruction_loss": reconstruction_loss,
            "kl_loss": kl_loss,
        }

vae = VAE(encoder, decoder)
vae.compile(optimizer=tf.keras.optimizers.Adam())

history = vae.fit(
    X_scaled,
    epochs=50,
    batch_size=32,
    shuffle=True
)

z_mean, z_log_var, z = encoder.predict(X_scaled)
num_samples = z.shape[0]
latent_dim = z.shape[1]

print(num_samples, latent_dim)

from sklearn.cluster import KMeans

num_clusters = 10  # GTZAN has 10 genres

kmeans_vae = KMeans(n_clusters=num_clusters, random_state=42)
vae_clusters = kmeans_vae.fit_predict(z)

from sklearn.metrics import silhouette_score, calinski_harabasz_score

silhouette_vae = silhouette_score(z, vae_clusters)
ch_vae = calinski_harabasz_score(z, vae_clusters)

print("VAE + KMeans")
print("Silhouette Score:", silhouette_vae)
print("Calinski-Harabasz Index:", ch_vae)

from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

pca = PCA(n_components=13)   # must be ≤ MFCC dimension
X_pca = pca.fit_transform(X_scaled)

kmeans_pca = KMeans(n_clusters=num_clusters, random_state=42)
pca_clusters = kmeans_pca.fit_predict(X_pca)

silhouette_pca = silhouette_score(X_pca, pca_clusters)
ch_pca = calinski_harabasz_score(X_pca, pca_clusters)

print("PCA + KMeans")
print("Silhouette Score:", silhouette_pca)
print("Calinski-Harabasz Index:", ch_pca)

from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

tsne = TSNE(n_components=2, random_state=42, perplexity=30)
z_tsne = tsne.fit_transform(z)

plt.figure(figsize=(8, 6))
plt.scatter(z_tsne[:, 0], z_tsne[:, 1], c=vae_clusters, cmap='tab10', s=10)
plt.colorbar(label="Cluster ID")
plt.title("t-SNE Visualization of VAE Latent Space")
plt.xlabel("Dimension 1")
plt.ylabel("Dimension 2")
plt.show()