# -*- coding: utf-8 -*-
"""425_Hard_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137ovynduBRDvXIwqAmc894-_L-0oTK3W
"""

!pip -q install librosa tqdm umap-learn soundfile

import os, random, math
import numpy as np
import pandas as pd
from tqdm import tqdm

import librosa
import soundfile as sf

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import (
    silhouette_score, calinski_harabasz_score, davies_bouldin_score,
    adjusted_rand_score, normalized_mutual_info_score
)

import umap
import matplotlib.pyplot as plt

!apt-get -qq update
!apt-get -qq install -y ffmpeg libsndfile1

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

GENRES_DIR = "/content/drive/MyDrive/CSE425_Easy_Task_Project/genres_original"
CSV_PATH_GIVEN = "/content/drive/MyDrive/CSE425_Easy_Task_Project/genres_original"

print("Genres folder exists:", os.path.isdir(GENRES_DIR))

# auto-find features_30_sec.csv inside the project folder
candidate_csvs = [
    CSV_PATH_GIVEN,  # might be wrong (folder)
    os.path.join("/content/drive/MyDrive/CSE425_Easy_Task_Project", "features_30_sec.csv"),
    os.path.join(GENRES_DIR, "features_30_sec.csv"),
    "/content/drive/MyDrive/CSE425_Easy_Task_Project/features_30_sec.csv",
    "/content/drive/MyDrive/CSE425_Easy_Task_Project/gtzan/features_30_sec.csv"
]

CSV_PATH = None
for p in candidate_csvs:
    if os.path.isfile(p) and p.endswith(".csv"):
        CSV_PATH = p
        break

if CSV_PATH is None:
    # try search in folder
    for root, _, files in os.walk("/content/drive/MyDrive/CSE425_Easy_Task_Project"):
        for f in files:
            if f.lower() == "features_30_sec.csv":
                CSV_PATH = os.path.join(root, f)
                break
        if CSV_PATH: break

print("Resolved CSV_PATH:", CSV_PATH)

assert CSV_PATH is not None, "features_30_sec.csv not found. Put it in your project folder and rerun."

df = pd.read_csv(CSV_PATH)
print("CSV shape:", df.shape)
print("CSV columns (first 10):", df.columns[:10].tolist())

# GTZAN features csv typically has 'filename' and 'label'
assert "filename" in df.columns, "CSV must have 'filename' column"
assert "label" in df.columns, "CSV must have 'label' column"

# Map filename -> label
csv_label_map = dict(zip(df["filename"].astype(str), df["label"].astype(str)))

print("Example filename:", df["filename"].iloc[0], "label:", df["label"].iloc[0])
print("Unique labels in CSV:", sorted(df["label"].unique())[:10], "... total:", df["label"].nunique())

# list genres from folders
genres = sorted([g for g in os.listdir(GENRES_DIR) if os.path.isdir(os.path.join(GENRES_DIR, g))])
print("Genres in folder:", genres)

audio_items = []
missing_in_csv = 0

for g in genres:
    gpath = os.path.join(GENRES_DIR, g)
    for f in os.listdir(gpath):
        if f.endswith(".wav"):
            # csv stores only filename, like 'blues.00000.wav'
            if f in csv_label_map:
                audio_items.append((os.path.join(gpath, f), csv_label_map[f]))
            else:
                missing_in_csv += 1

print("Audio items aligned with CSV:", len(audio_items))
print("Audio files missing in CSV:", missing_in_csv)

# label encoder
le = LabelEncoder()
all_labels = [lab for _, lab in audio_items]
le.fit(all_labels)
num_classes = len(le.classes_)
print("Classes:", list(le.classes_))
print("num_classes:", num_classes)

def wav_to_logmel(
    file_path,
    sr=22050,
    duration=30.0,
    n_fft=2048,
    hop_length=512,
    n_mels=128,
    fmin=20,
    fmax=8000,
    target_frames=256
):
    try:
        y, _sr = librosa.load(file_path, sr=sr, duration=duration, mono=True)
    except Exception:
        try:
            y, sr_native = sf.read(file_path, always_2d=False)
            if y.ndim > 1:
                y = np.mean(y, axis=1)
            if sr_native != sr:
                y = librosa.resample(y.astype(np.float32), orig_sr=sr_native, target_sr=sr)
        except Exception:
            return None

    target_len = int(sr * duration)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]

    mel = librosa.feature.melspectrogram(
        y=y, sr=sr, n_fft=n_fft, hop_length=hop_length,
        n_mels=n_mels, fmin=fmin, fmax=fmax, power=2.0
    )
    logmel = librosa.power_to_db(mel, ref=np.max)

    # normalize per-sample
    logmel = (logmel - logmel.mean()) / (logmel.std() + 1e-8)

    T = logmel.shape[1]
    if T < target_frames:
        logmel = np.pad(logmel, ((0,0),(0,target_frames - T)))
    else:
        logmel = logmel[:, :target_frames]

    return logmel.astype(np.float32)[None, :, :]  # (1, 128, 256)

class GTZAN_CVAE_Dataset(Dataset):
    def __init__(self, audio_items, label_encoder):
        self.items = []
        bad = 0
        for path, lab in tqdm(audio_items, desc="Checking audio"):
            x = wav_to_logmel(path)
            if x is None:
                bad += 1
                continue
            y = int(label_encoder.transform([lab])[0])
            self.items.append((path, y))
        self.num_classes = len(label_encoder.classes_)
        print(f"[Dataset] usable={len(self.items)} skipped_bad={bad}")

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, y = self.items[idx]
        x = wav_to_logmel(path)
        if x is None:
            x = np.zeros((1,128,256), dtype=np.float32)
        c = np.zeros((self.num_classes,), dtype=np.float32)
        c[y] = 1.0
        return torch.from_numpy(x), torch.tensor(y), torch.from_numpy(c), path

ds = GTZAN_CVAE_Dataset(audio_items, le)

# sanity check
x0, y0, c0, p0 = ds[0]
print("x:", x0.shape, "y:", y0.item(), "c:", c0.shape, "path:", os.path.basename(p0))

N = len(ds)
train_size = int(0.8 * N)
val_size = N - train_size
train_ds, val_ds = random_split(ds, [train_size, val_size], generator=torch.Generator().manual_seed(42))

BATCH_SIZE = 32
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print("Train:", len(train_ds), "Val:", len(val_ds))

class ConditionalConvVAE(nn.Module):
    def __init__(self, latent_dim=16, num_classes=10):
        super().__init__()
        self.latent_dim = latent_dim
        self.num_classes = num_classes

        # Encoder CNN: (B,1,128,256) -> (B,256,8,16)
        self.enc = nn.Sequential(
            nn.Conv2d(1, 32, 4, 2, 1), nn.ReLU(),   # 64x128
            nn.Conv2d(32, 64, 4, 2, 1), nn.ReLU(),  # 32x64
            nn.Conv2d(64, 128, 4, 2, 1), nn.ReLU(), # 16x32
            nn.Conv2d(128, 256, 4, 2, 1), nn.ReLU() # 8x16
        )

        self.flat_dim = 256 * 8 * 16

        # condition added before mu/logvar
        self.fc_h = nn.Linear(self.flat_dim + num_classes, 256)
        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_logvar = nn.Linear(256, latent_dim)

        # decoder: latent + condition
        self.fc_dec = nn.Linear(latent_dim + num_classes, self.flat_dim)

        self.dec = nn.Sequential(
            nn.ConvTranspose2d(256, 128, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(128, 64, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, 2, 1), nn.ReLU(),
            nn.ConvTranspose2d(32, 1, 4, 2, 1)
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x, c):
        h = self.enc(x).view(x.size(0), -1)
        h = torch.cat([h, c], dim=1)
        h = F.relu(self.fc_h(h))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        z = self.reparameterize(mu, logvar)

        zc = torch.cat([z, c], dim=1)
        h2 = self.fc_dec(zc).view(x.size(0), 256, 8, 16)
        x_hat = self.dec(h2)
        return x_hat, mu, logvar, z

def cvae_loss(x, x_hat, mu, logvar, beta=4.0):
    recon = F.mse_loss(x_hat, x, reduction="sum") / x.size(0)
    kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()) / x.size(0)
    return recon + beta * kl, recon, kl

LATENT_DIM = 16
BETA = 4.0
LR = 1e-3
EPOCHS = 25

model = ConditionalConvVAE(latent_dim=LATENT_DIM, num_classes=num_classes).to(device)
opt = torch.optim.Adam(model.parameters(), lr=LR)

def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    total, total_r, total_k = 0.0, 0.0, 0.0
    nb = 0
    for x, y, c, _ in loader:
        x, c = x.to(device), c.to(device)

        with torch.set_grad_enabled(train):
            x_hat, mu, logvar, _ = model(x, c)
            loss, recon, kl = cvae_loss(x, x_hat, mu, logvar, beta=BETA)

            if train:
                opt.zero_grad()
                loss.backward()
                opt.step()

        total += loss.item()
        total_r += recon.item()
        total_k += kl.item()
        nb += 1

    return total/nb, total_r/nb, total_k/nb

hist = {"train":[], "val":[]}

for ep in range(1, EPOCHS+1):
    tr = run_epoch(train_loader, train=True)
    va = run_epoch(val_loader, train=False)
    hist["train"].append(tr)
    hist["val"].append(va)
    print(f"Ep {ep:02d}/{EPOCHS} | "
          f"Train L={tr[0]:.2f} (R={tr[1]:.2f}, KL={tr[2]:.2f}) | "
          f"Val L={va[0]:.2f} (R={va[1]:.2f}, KL={va[2]:.2f})")

plt.figure(figsize=(8,5))
plt.plot([x[0] for x in hist["train"]], label="train_total")
plt.plot([x[0] for x in hist["val"]], label="val_total")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(f"Hard Task CVAE (beta={BETA}) Training Curve")
plt.legend()
plt.show()

model.eval()

Z_list, Y_list = [], []
loader_all = DataLoader(ds, batch_size=32, shuffle=False, num_workers=0)

with torch.no_grad():
    for x, y, c, _ in tqdm(loader_all, total=len(loader_all), desc="Extracting latents"):
        x, c = x.to(device), c.to(device)
        _, mu, _, _ = model(x, c)
        Z_list.append(mu.cpu().numpy())
        Y_list.append(y.numpy())

Z = np.vstack(Z_list)
Y = np.concatenate(Y_list)

print("Z shape:", Z.shape, "Y shape:", Y.shape)

scaler = StandardScaler()
Zs = scaler.fit_transform(Z)
print("Zs mean:", Zs.mean(), "Zs std:", Zs.std())

def cluster_purity(y_true, y_pred):
    # y_true: ints, y_pred: cluster ids
    total = 0
    for k in np.unique(y_pred):
        idx = (y_pred == k)
        if idx.sum() == 0:
            continue
        counts = np.bincount(y_true[idx])
        total += counts.max()
    return total / len(y_true)

def clustering_report(Z_use, y_true, name, y_pred):
    # core cluster metrics
    sil = silhouette_score(Z_use, y_pred) if len(np.unique(y_pred)) > 1 else np.nan
    ch  = calinski_harabasz_score(Z_use, y_pred) if len(np.unique(y_pred)) > 1 else np.nan
    db  = davies_bouldin_score(Z_use, y_pred) if len(np.unique(y_pred)) > 1 else np.nan

    # label-based metrics (evaluation only)
    ari = adjusted_rand_score(y_true, y_pred)
    nmi = normalized_mutual_info_score(y_true, y_pred)
    pur = cluster_purity(y_true, y_pred)

    print(f"\n{name}")
    print("Silhouette:", sil)
    print("Calinski-Harabasz:", ch)
    print("Davies-Bouldin (lower better):", db)
    print("ARI:", ari)
    print("NMI:", nmi)
    print("Purity:", pur)

NUM_CLUSTERS = num_classes

pred_km = KMeans(n_clusters=NUM_CLUSTERS, random_state=42, n_init=10).fit_predict(Zs)
pred_ag = AgglomerativeClustering(n_clusters=NUM_CLUSTERS, linkage="ward").fit_predict(Zs)

clustering_report(Zs, Y, "Hard CVAE Latent + KMeans", pred_km)
clustering_report(Zs, Y, "Hard CVAE Latent + Agglomerative", pred_ag)

import numpy as np
import matplotlib.pyplot as plt

# Ensure these exist:
# pred_km (KMeans cluster assignments), Y (true genre ids), le (LabelEncoder)

cluster_ids = np.unique(pred_km)
genre_names = le.classes_
n_clusters = len(cluster_ids)
n_genres = len(genre_names)

# Build cluster x genre count matrix
dist = np.zeros((n_clusters, n_genres), dtype=int)

for i, cid in enumerate(cluster_ids):
    idx = (pred_km == cid)
    counts = np.bincount(Y[idx], minlength=n_genres)
    dist[i] = counts

# Plot stacked bar: each cluster shows composition by true genre
plt.figure(figsize=(14,5))
bottom = np.zeros(n_clusters)

for g in range(n_genres):
    plt.bar(cluster_ids, dist[:, g], bottom=bottom, label=genre_names[g])
    bottom += dist[:, g]

plt.title("Cluster Composition by True Genre (Hard CVAE Latent + KMeans)")
plt.xlabel("Cluster ID")
plt.ylabel("Number of Tracks")
plt.xticks(cluster_ids)
plt.legend(bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

# Print per-cluster purity + dominant genre
print("\nPer-cluster purity and dominant genre:")
for i, cid in enumerate(cluster_ids):
    total = dist[i].sum()
    dom_idx = dist[i].argmax()
    dom_genre = genre_names[dom_idx]
    purity_i = dist[i, dom_idx] / total if total > 0 else 0.0
    print(f"Cluster {cid:>2}: size={total:>4}  dominant={dom_genre:<10}  purity={purity_i:.3f}")

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, silhouette_score
import numpy as np
import torch

# You must already have these from your notebook:
# - ConditionalConvVAE class
# - cvae_loss function (takes beta argument)
# - train_loader, val_loader, ds
# - device
# - num_classes
# - cluster_purity function
# - set_seed function

BETAS = [1.0, 2.0, 4.0, 6.0]
EPOCHS_SWEEP = 10      # fast sweep; increase to 12-15 if you want
LATENT_DIM = 16
LR = 1e-3

def train_cvae_for_beta(beta, epochs=EPOCHS_SWEEP):
    set_seed(42)
    model_b = ConditionalConvVAE(latent_dim=LATENT_DIM, num_classes=num_classes).to(device)
    opt_b = torch.optim.Adam(model_b.parameters(), lr=LR)

    def run_epoch(loader, train=True):
        model_b.train() if train else model_b.eval()
        total = 0.0
        nb = 0
        for x, y, c, _ in loader:
            x, c = x.to(device), c.to(device)
            with torch.set_grad_enabled(train):
                x_hat, mu, logvar, _ = model_b(x, c)
                loss, recon, kl = cvae_loss(x, x_hat, mu, logvar, beta=beta)
                if train:
                    opt_b.zero_grad()
                    loss.backward()
                    opt_b.step()
            total += loss.item()
            nb += 1
        return total / nb

    for ep in range(1, epochs + 1):
        tr = run_epoch(train_loader, train=True)
        va = run_epoch(val_loader, train=False)
        if ep == 1 or ep == epochs or ep % 5 == 0:
            print(f"beta={beta}  ep={ep:02d}/{epochs}  train_loss={tr:.1f}  val_loss={va:.1f}")

    return model_b

def extract_mu(model_b):
    model_b.eval()
    Z_list, Y_list = [], []
    loader_all = DataLoader(ds, batch_size=32, shuffle=False, num_workers=0)
    with torch.no_grad():
        for x, y, c, _ in loader_all:
            x, c = x.to(device), c.to(device)
            _, mu, _, _ = model_b(x, c)
            Z_list.append(mu.cpu().numpy())
            Y_list.append(y.numpy())
    Z = np.vstack(Z_list)
    Y = np.concatenate(Y_list)
    return Z, Y

def eval_by_kmeans(Z, Y, k):
    Zs_local = StandardScaler().fit_transform(Z)
    pred = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(Zs_local)

    ari = adjusted_rand_score(Y, pred)
    nmi = normalized_mutual_info_score(Y, pred)
    pur = cluster_purity(Y, pred)
    sil = silhouette_score(Zs_local, pred) if len(np.unique(pred)) > 1 else np.nan

    return {"ARI": ari, "NMI": nmi, "Purity": pur, "Silhouette": sil}

sweep_rows = []
models_by_beta = {}

print("\n====================")
print("β SWEEP START")
print("====================")

for b in BETAS:
    print("\n--------------------")
    print("Training for beta =", b)
    m_b = train_cvae_for_beta(b, epochs=EPOCHS_SWEEP)
    Z_b, Y_b = extract_mu(m_b)
    metrics_b = eval_by_kmeans(Z_b, Y_b, k=num_classes)
    print("Metrics:", metrics_b)
    sweep_rows.append((b, metrics_b))
    models_by_beta[b] = m_b

# Pick best by NMI (primary) then ARI (secondary)
best_beta = sorted(sweep_rows, key=lambda t: (t[1]["NMI"], t[1]["ARI"]), reverse=True)[0][0]
best_metrics = [m for b,m in sweep_rows if b == best_beta][0]

print("\n✅ β SWEEP DONE")
print("Best beta:", best_beta)
print("Best metrics:", best_metrics)

# OPTIONAL: retrain best beta longer for final results (recommended)
RETRAIN_BEST = True
EPOCHS_FINAL = 25

if RETRAIN_BEST:
    print("\n====================")
    print(f"Retraining best beta={best_beta} for {EPOCHS_FINAL} epochs (final model)")
    print("====================")
    final_model = train_cvae_for_beta(best_beta, epochs=EPOCHS_FINAL)
    Z_final, Y_final = extract_mu(final_model)
    final_metrics = eval_by_kmeans(Z_final, Y_final, k=num_classes)
    print("\n✅ FINAL (best beta) metrics:", final_metrics)

    # Save for later cells if you want:
    model = final_model
    Z = Z_final
    Y = Y_final
    Zs = StandardScaler().fit_transform(Z)
    pred_km = KMeans(n_clusters=num_classes, random_state=42, n_init=10).fit_predict(Zs)

um = umap.UMAP(n_components=2, random_state=42)
Z2 = um.fit_transform(Zs)

plt.figure(figsize=(8,6))
plt.scatter(Z2[:,0], Z2[:,1], c=pred_km, s=10, cmap="tab20")
plt.colorbar(label="KMeans Cluster")
plt.title("UMAP of Hard CVAE Latent (colored by cluster)")
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(Z2[:,0], Z2[:,1], c=Y, s=10, cmap="tab10")
plt.colorbar(label="True Genre ID")
plt.title("UMAP of Hard CVAE Latent (colored by true genre)")
plt.show()

model.eval()
x, y, c, _ = next(iter(val_loader))
x, c = x.to(device), c.to(device)

with torch.no_grad():
    x_hat, _, _, _ = model(x, c)

x_np  = x[0,0].cpu().numpy()
xh_np = x_hat[0,0].cpu().numpy()

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.imshow(x_np, aspect="auto", origin="lower")
plt.title("Original Log-Mel")
plt.colorbar()

plt.subplot(1,2,2)
plt.imshow(xh_np, aspect="auto", origin="lower")
plt.title("Reconstructed Log-Mel")
plt.colorbar()

plt.tight_layout()
plt.show()

# Prepare CSV feature matrix
df2 = df.copy()
# Keep only rows used in audio_items (aligned filenames)
aligned_files = set([os.path.basename(p) for p,_ in audio_items])
df2 = df2[df2["filename"].astype(str).isin(aligned_files)].reset_index(drop=True)

# X_csv = drop non-numeric + label + filename
drop_cols = ["filename", "label"]
X_csv = df2.drop(columns=[c for c in drop_cols if c in df2.columns])

# keep numeric only
X_csv = X_csv.select_dtypes(include=[np.number]).fillna(0.0).values

y_csv = le.transform(df2["label"].astype(str).values)

print("X_csv shape:", X_csv.shape, "y_csv shape:", y_csv.shape)

X_csvs = StandardScaler().fit_transform(X_csv)
Xp = PCA(n_components=16, random_state=42).fit_transform(X_csvs)

pred_pca_km = KMeans(n_clusters=NUM_CLUSTERS, random_state=42, n_init=10).fit_predict(Xp)

clustering_report(Xp, y_csv, "Baseline: PCA(16) on CSV + KMeans", pred_pca_km)

class TabularAE(nn.Module):
    def __init__(self, in_dim, latent_dim=16):
        super().__init__()
        self.enc = nn.Sequential(
            nn.Linear(in_dim, 128), nn.ReLU(),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, latent_dim)
        )
        self.dec = nn.Sequential(
            nn.Linear(latent_dim, 64), nn.ReLU(),
            nn.Linear(64, 128), nn.ReLU(),
            nn.Linear(128, in_dim)
        )

    def forward(self, x):
        z = self.enc(x)
        x_hat = self.dec(z)
        return x_hat, z

X_t = torch.tensor(X_csvs, dtype=torch.float32).to(device)

ae = TabularAE(in_dim=X_csvs.shape[1], latent_dim=16).to(device)
opt2 = torch.optim.Adam(ae.parameters(), lr=1e-3)

for ep in range(1, 51):
    ae.train()
    x_hat, z = ae(X_t)
    loss = F.mse_loss(x_hat, X_t)
    opt2.zero_grad(); loss.backward(); opt2.step()
    if ep % 10 == 0:
        print(f"AE epoch {ep}/50 loss={loss.item():.4f}")

ae.eval()
with torch.no_grad():
    _, Z_ae = ae(X_t)
Z_ae = Z_ae.cpu().numpy()

pred_ae_km = KMeans(n_clusters=NUM_CLUSTERS, random_state=42, n_init=10).fit_predict(Z_ae)

clustering_report(Z_ae, y_csv, "Baseline: Autoencoder(CSV latent) + KMeans", pred_ae_km)

