# -*- coding: utf-8 -*-
"""425_Medium_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoFU2OXcZWjQwaBDJEFH0vweAKnHc9yy
"""

!pip -q install librosa tqdm umap-learn

import os, random, math, time
import numpy as np
from tqdm import tqdm

import librosa
import librosa.display

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score, adjusted_rand_score
from sklearn.manifold import TSNE
import umap

import matplotlib.pyplot as plt

!apt-get -qq update
!apt-get -qq install -y ffmpeg libsndfile1
!pip -q install soundfile audioread

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

DATASET_PATH = "/content/drive/MyDrive/CSE425_Easy_Task_Project/genres_original"  # change if needed

genres = sorted([g for g in os.listdir(DATASET_PATH) if os.path.isdir(os.path.join(DATASET_PATH, g))])
print("Genres found:", genres)
print("Total genres:", len(genres))

# count files
total = 0
for g in genres:
    total += len([f for f in os.listdir(os.path.join(DATASET_PATH, g)) if f.endswith(".wav")])
print("Total .wav files:", total)

import soundfile as sf

def wav_to_logmel(
    file_path,
    sr=22050,
    duration=30.0,
    n_fft=2048,
    hop_length=512,
    n_mels=128,
    fmin=20,
    fmax=8000,
    target_frames=256
):
    try:
        y, sr = librosa.load(file_path, sr=sr, duration=duration, mono=True)
    except Exception:
        # fallback to soundfile
        try:
            y, sr_native = sf.read(file_path, always_2d=False)
            if y.ndim > 1:
                y = np.mean(y, axis=1)  # stereo -> mono
            # resample if needed
            if sr_native != sr:
                y = librosa.resample(y.astype(np.float32), orig_sr=sr_native, target_sr=sr)
        except Exception as e:
            # cannot decode this file
            return None

    # pad/cut to fixed duration
    target_len = int(sr * duration)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]

    mel = librosa.feature.melspectrogram(
        y=y, sr=sr, n_fft=n_fft, hop_length=hop_length,
        n_mels=n_mels, fmin=fmin, fmax=fmax, power=2.0
    )
    logmel = librosa.power_to_db(mel, ref=np.max)

    logmel = (logmel - logmel.mean()) / (logmel.std() + 1e-8)

    T = logmel.shape[1]
    if T < target_frames:
        logmel = np.pad(logmel, ((0,0),(0,target_frames - T)))
    else:
        logmel = logmel[:, :target_frames]

    return logmel.astype(np.float32)[None, :, :]

genre_to_id = {g:i for i,g in enumerate(genres)}
id_to_genre = {i:g for g,i in genre_to_id.items()}

class GTZANLogMelDataset(Dataset):
    def __init__(self, root_dir):
        self.items = []
        bad = 0

        for g in genres:
            gpath = os.path.join(root_dir, g)
            for f in os.listdir(gpath):
                if f.endswith(".wav"):
                    full = os.path.join(gpath, f)
                    x = wav_to_logmel(full)
                    if x is None:
                        bad += 1
                        continue
                    self.items.append((full, genre_to_id[g]))

        print(f"[Dataset] Loaded {len(self.items)} usable files. Skipped {bad} bad files.")

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        path, y = self.items[idx]
        x = wav_to_logmel(path)
        # x should never be None now, but keep safe
        if x is None:
            x = np.zeros((1, 128, 256), dtype=np.float32)
        return torch.from_numpy(x), y, path

ds = GTZANLogMelDataset(DATASET_PATH)

from torch.utils.data import random_split

N = len(ds)
train_size = int(0.8 * N)
val_size = N - train_size
train_ds, val_ds = random_split(ds, [train_size, val_size], generator=torch.Generator().manual_seed(42))

BATCH_SIZE = 32
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)


print("Train:", len(train_ds), "Val:", len(val_ds))

class ConvVAE(nn.Module):
    def __init__(self, latent_dim=16):
        super().__init__()
        self.latent_dim = latent_dim

        # Input: (B, 1, 128, 256)
        self.enc = nn.Sequential(
            nn.Conv2d(1, 32, 4, 2, 1),   # (B, 32, 64, 128)
            nn.ReLU(),
            nn.Conv2d(32, 64, 4, 2, 1),  # (B, 64, 32, 64)
            nn.ReLU(),
            nn.Conv2d(64, 128, 4, 2, 1), # (B, 128, 16, 32)
            nn.ReLU(),
            nn.Conv2d(128, 256, 4, 2, 1) # (B, 256, 8, 16)
        )

        self.flatten_dim = 256 * 8 * 16
        self.fc_mu = nn.Linear(self.flatten_dim, latent_dim)
        self.fc_logvar = nn.Linear(self.flatten_dim, latent_dim)

        self.fc_dec = nn.Linear(latent_dim, self.flatten_dim)

        self.dec = nn.Sequential(
            nn.ConvTranspose2d(256, 128, 4, 2, 1), # (B, 128, 16, 32)
            nn.ReLU(),
            nn.ConvTranspose2d(128, 64, 4, 2, 1),  # (B, 64, 32, 64)
            nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, 2, 1),   # (B, 32, 64, 128)
            nn.ReLU(),
            nn.ConvTranspose2d(32, 1, 4, 2, 1)     # (B, 1, 128, 256)
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def forward(self, x):
        h = self.enc(x)
        h = h.view(x.size(0), -1)
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        z = self.reparameterize(mu, logvar)

        h2 = self.fc_dec(z).view(x.size(0), 256, 8, 16)
        x_hat = self.dec(h2)
        return x_hat, mu, logvar, z

def vae_loss(x, x_hat, mu, logvar, beta=1.0):
    # reconstruction loss
    recon = F.mse_loss(x_hat, x, reduction="sum") / x.size(0)
    # KL divergence
    kl = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp()) / x.size(0)
    return recon + beta * kl, recon, kl

model = ConvVAE(latent_dim=16).to(device)
print(model)

LR = 5e-4
EPOCHS = 25
BETA = 1.0

opt = torch.optim.Adam(model.parameters(), lr=LR)

def run_epoch(loader, train=True):
    model.train() if train else model.eval()
    total_loss, total_recon, total_kl = 0.0, 0.0, 0.0
    n_batches = 0

    for x, _, _ in loader:
        x = x.to(device)

        with torch.set_grad_enabled(train):
            x_hat, mu, logvar, _ = model(x)
            loss, recon, kl = vae_loss(x, x_hat, mu, logvar, beta=BETA)

            if train:
                opt.zero_grad()
                loss.backward()
                opt.step()

        total_loss += loss.item()
        total_recon += recon.item()
        total_kl += kl.item()
        n_batches += 1

    return total_loss / n_batches, total_recon / n_batches, total_kl / n_batches

history = {"train":[], "val":[]}

for ep in range(1, EPOCHS+1):
    tr = run_epoch(train_loader, train=True)
    va = run_epoch(val_loader, train=False)
    history["train"].append(tr)
    history["val"].append(va)

    print(f"Epoch {ep:02d}/{EPOCHS} | "
          f"Train Loss={tr[0]:.4f} (Recon={tr[1]:.4f}, KL={tr[2]:.4f}) | "
          f"Val Loss={va[0]:.4f} (Recon={va[1]:.4f}, KL={va[2]:.4f})")



train_loss = [x[0] for x in history["train"]]
val_loss   = [x[0] for x in history["val"]]

plt.figure(figsize=(8,5))
plt.plot(train_loss, label="train_loss")
plt.plot(val_loss, label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Conv-VAE Training Curve")
plt.legend()
plt.show()

model.eval()

all_mu = []
all_y = []
all_paths = []

loader_all = DataLoader(ds, batch_size=32, shuffle=False, num_workers=2)
with torch.no_grad():
    for x, y, paths in tqdm(loader_all, total=len(loader_all)):
        x = x.to(device)
        _, mu, _, _ = model(x)
        all_mu.append(mu.cpu().numpy())
        all_y.append(np.array(y))
        all_paths.extend(list(paths))

Z = np.vstack(all_mu)              # (N, latent_dim)
Y = np.concatenate(all_y)          # (N,)
print("Latent Z shape:", Z.shape, "Labels Y shape:", Y.shape)

scaler = StandardScaler()
Zs = scaler.fit_transform(Z)

print("Zs mean (approx):", Zs.mean(axis=0)[:5])
print("Zs std  (approx):", Zs.std(axis=0)[:5])

from sklearn.cluster import DBSCAN
import numpy as np

def dbscan_summary(Z_use, eps, min_samples):
    pred = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(Z_use)
    uniq, counts = np.unique(pred, return_counts=True)
    noise = counts[uniq == -1][0] if -1 in uniq else 0
    n_clusters = len(uniq) - (1 if -1 in uniq else 0)
    return pred, n_clusters, noise, len(pred)

eps_list = [0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.4,1.6,1.8,2.0]
min_samples_list = [3,5,8,10]

for ms in min_samples_list:
    print(f"\n--- min_samples={ms} ---")
    for eps in eps_list:
        _, k, noise, n = dbscan_summary(Zs, eps, ms)
        print(f"eps={eps:<3}  clusters={k:<2}  noise={noise}/{n}")

from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score, adjusted_rand_score

def dbscan_metrics(Z_use, pred, true_labels=None):
    mask = pred != -1
    if mask.sum() < 10 or len(np.unique(pred[mask])) < 2:
        return None

    Zm = Z_use[mask]
    pm = pred[mask]

    sil = silhouette_score(Zm, pm)
    ch  = calinski_harabasz_score(Zm, pm)
    db  = davies_bouldin_score(Zm, pm)

    out = {
        "sil": sil,
        "ch": ch,
        "db": db,
        "clusters": len(np.unique(pm)),
        "kept": mask.sum()
    }

    if true_labels is not None:
        out["ari"] = adjusted_rand_score(true_labels[mask], pm)

    return out

results = []

for ms in min_samples_list:
    for eps in eps_list:
        pred, _, noise, n = dbscan_summary(Zs, eps, ms)
        m = dbscan_metrics(Zs, pred, Y)
        if m is None:
            continue
        m.update({
            "eps": eps,
            "min_samples": ms,
            "noise_pct": 100.0 * noise / n
        })
        results.append(m)

results_sorted = sorted(
    results,
    key=lambda d: (d["sil"], -d.get("ari", 0), -d["ch"]),
    reverse=True
)

print("Top DBSCAN configurations:")
for r in results_sorted[:5]:
    print(r)

NUM_CLUSTERS = 10

# 1) KMeans
km = KMeans(n_clusters=NUM_CLUSTERS, random_state=42, n_init=10)
pred_km = km.fit_predict(Zs)

# 2) Agglomerative
agg = AgglomerativeClustering(n_clusters=NUM_CLUSTERS, linkage="ward")
pred_agg = agg.fit_predict(Zs)

# 3) DBSCAN (tune eps if too many -1)
# db = DBSCAN(eps=1.5, min_samples=5)   # try eps=1.2 or 1.8 if needed
# pred_db = db.fit_predict(Zs)
best = results_sorted[0]

best_eps = best["eps"]
best_ms = best["min_samples"]

print("Chosen DBSCAN config:", best)

db = DBSCAN(eps=best_eps, min_samples=best_ms)
pred_db = db.fit_predict(Zs)

print("Unique clusters DBSCAN:", np.unique(pred_db, return_counts=True))
print("Noise %:", (pred_db == -1).mean() * 100)

print("Unique clusters KMeans:", np.unique(pred_km))
print("Unique clusters Agglo :", np.unique(pred_agg))

def safe_metrics(Z_use, pred, true_labels=None, name="method"):
    uniq = np.unique(pred)
    if len(uniq) < 2:
        print(f"\n{name}: Not enough clusters for metrics (unique={uniq})")
        return

    # if DBSCAN has noise, remove noise for silhouette/CH/DB
    mask = np.ones(len(pred), dtype=bool)
    if -1 in uniq:
        mask = pred != -1
        if mask.sum() < 10 or len(np.unique(pred[mask])) < 2:
            print(f"\n{name}: DBSCAN produced too much noise for metrics.")
            return

    Zm = Z_use[mask]
    pm = pred[mask]

    sil = silhouette_score(Zm, pm)
    ch  = calinski_harabasz_score(Zm, pm)
    db  = davies_bouldin_score(Zm, pm)

    print(f"\n{name}")
    print("Silhouette:", sil)
    print("Calinski-Harabasz:", ch)
    print("Davies-Bouldin (lower better):", db)

    if true_labels is not None:
        ari = adjusted_rand_score(true_labels[mask], pm)
        print("ARI (using genre labels only for evaluation):", ari)

safe_metrics(Zs, pred_km, Y, "ConvVAE Latent + KMeans")
safe_metrics(Zs, pred_agg, Y, "ConvVAE Latent + Agglomerative")
safe_metrics(Zs, pred_db, Y, "ConvVAE Latent + DBSCAN")

tsne = TSNE(n_components=2, random_state=42, perplexity=30)
Z_tsne = tsne.fit_transform(Zs)

plt.figure(figsize=(8,6))
plt.scatter(Z_tsne[:,0], Z_tsne[:,1], c=pred_km, s=10, cmap="tab10")
plt.colorbar(label="Cluster ID")
plt.title("t-SNE of ConvVAE Latent Space (Colored by KMeans)")
plt.xlabel("Dim-1"); plt.ylabel("Dim-2")
plt.show()

um = umap.UMAP(n_components=2, random_state=42)
Z_umap = um.fit_transform(Zs)

plt.figure(figsize=(8,6))
plt.scatter(Z_umap[:,0], Z_umap[:,1], c=pred_km, s=10, cmap="tab10")
plt.colorbar(label="Cluster ID")
plt.title("UMAP of ConvVAE Latent Space (Colored by KMeans)")
plt.xlabel("Dim-1"); plt.ylabel("Dim-2")
plt.show()

# show original vs reconstructed log-mel
model.eval()
x, y, _ = next(iter(val_loader))
x = x.to(device)

with torch.no_grad():
    x_hat, _, _, _ = model(x)

x_np = x[0,0].cpu().numpy()
xh_np = x_hat[0,0].cpu().numpy()

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.imshow(x_np, aspect="auto", origin="lower")
plt.title("Original Log-Mel")
plt.colorbar()

plt.subplot(1,2,2)
plt.imshow(xh_np, aspect="auto", origin="lower")
plt.title("Reconstructed Log-Mel")
plt.colorbar()
plt.tight_layout()
plt.show()